repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: forbid-new-submodules
          - id: trailing-whitespace
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.36.0
      hooks:
          - id: markdownlint
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v16.0.6
      hooks:
          - id: clang-format
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            args:
                - --config-precedence=file-override
            additional_dependencies:
                - prettier@2.4.1
                - prettier-plugin-toml@0.3.1
    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            language_version: python3.9
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
