name: test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository and submodules
              uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Run tests
              uses: ./.devcontainer
              with:
                  args: make all
            - name: Run tests with config
              uses: ./.devcontainer
              with:
                  args: make all AUTOFFF_CONFIG=config.ini
